#!/bin/bash
# $1 -- первая модель, $2 -- вторая модель, $3 -- число итераций
name_cnf="equal_models_$1_and_$2_input"
for ((var = 1; var <= $3; var++)); do
  echo "----------------------------------------$var-------------------------------------->>"
  path_res="../../../data/res_minisatcs/res_$name_cnf$var.txt"
  input_path="../../../data/res_minisatcs/input_$name_cnf$var.txt"

  python3 ./generate_input.py $1 $2 > $input_path
  ../../../solvers/minisatcs/minisat ../../../data/CNFs/$name_cnf.cnf $path_res
  python3 ./check_res.py $input_path $path_res
  echo "<<--------------------------------------$var----------------------------------------"
done