from src.create_model.model import Model


def create_model0():
    model = Model("model0")
    model.add_init()
    model.add_flatten()
    model.add_output(units=10)
    model.save()


def create_model1():
    model = Model("model1")
    model.add_init()
    model.add_quant_conv2D_maxpooling2D(kernel_size=32, strides=(3, 3), pool_size=(2, 2), input_shape=(28, 28, 1))
    model.add_flatten()
    model.add_output(units=10)
    model.save()


def create_model2():
    model = Model("model2")
    model.add_init()
    model.add_quant_conv2D_maxpooling2D(kernel_size=32, strides=(3, 3), pool_size=(2, 2), input_shape=(28, 28, 1))
    model.add_flatten()
    model.add_quant_dense(units=64)
    model.add_output(units=10)
    model.save()


def create_model3():
    model = Model("model3")
    model.add_init()
    model.add_quant_conv2D_maxpooling2D(kernel_size=32, strides=(3, 3), pool_size=(2, 2), input_shape=(28, 28, 1))
    model.add_quant_conv2D_maxpooling2D(kernel_size=64, strides=(3, 3), pool_size=(2, 2))
    model.add_quant_conv2D(kernel_size=64, strides=(3, 3))
    model.add_flatten()
    model.add_quant_dense(units=64)
    model.add_output(units=10)
    model.save()


def create_model4():
    model = Model("model4")
    model.add_init()
    model.add_flatten()
    model.add_quant_dense(units=32)
    model.add_output(units=10)
    model.save()


def create_model5():
    model = Model("model5")
    model.add_init()
    model.add_flatten()
    model.add_quant_dense(units=32)
    model.add_quant_dense(units=64)
    model.add_quant_dense(units=128)
    model.add_output(units=10)
    model.save()


def create_model6(): # 19
    model = Model("model6")
    model.add_init()
    model.add_flatten()
    model.add_quant_dense(units=32)
    model.add_quant_dense(units=64)
    model.add_quant_dense(units=128)
    model.add_quant_dense(units=256)
    model.add_quant_dense(units=128)
    model.add_quant_dense(units=64)
    model.add_quant_dense(units=64)
    model.add_quant_dense(units=128)
    model.add_quant_dense(units=256)
    model.add_quant_dense(units=512)
    model.add_quant_dense(units=1024)
    model.add_quant_dense(units=512)
    model.add_quant_dense(units=128)
    model.add_quant_dense(units=64)
    model.add_quant_dense(units=32)
    model.add_quant_dense(units=21)
    model.add_output(units=10)
    model.save()


def create_model7(): # 99
    model = Model("model7")
    model.add_init()
    model.add_flatten()
    model.add_quant_dense(units=32)
    model.add_quant_dense(units=64)
    model.add_quant_dense(units=128)
    model.add_quant_dense(units=256)
    model.add_quant_dense(units=128)
    model.add_quant_dense(units=64)
    model.add_quant_dense(units=64)
    model.add_quant_dense(units=128)
    model.add_quant_dense(units=256)
    model.add_quant_dense(units=512)
    model.add_quant_dense(units=812)
    model.add_quant_dense(units=1024)
    model.add_quant_dense(units=1523)
    model.add_quant_dense(units=1854)
    model.add_quant_dense(units=2048)
    model.add_quant_dense(units=1854)
    model.add_quant_dense(units=1523)
    model.add_quant_dense(units=1024)
    model.add_quant_dense(units=812)
    model.add_quant_dense(units=512)
    model.add_quant_dense(units=128)
    model.add_quant_dense(units=64)
    model.add_quant_dense(units=32)
    model.add_quant_dense(units=21)
    model.add_quant_dense(units=32)
    model.add_quant_dense(units=64)
    model.add_quant_dense(units=128)
    model.add_quant_dense(units=256)
    model.add_quant_dense(units=128)
    model.add_quant_dense(units=64)
    model.add_quant_dense(units=64)
    model.add_quant_dense(units=128)
    model.add_quant_dense(units=256)
    model.add_quant_dense(units=512)
    model.add_quant_dense(units=812)
    model.add_quant_dense(units=1024)
    model.add_quant_dense(units=1523)
    model.add_quant_dense(units=1854)
    model.add_quant_dense(units=2048)
    model.add_quant_dense(units=1854)
    model.add_quant_dense(units=1523)
    model.add_quant_dense(units=1024)
    model.add_quant_dense(units=812)
    model.add_quant_dense(units=512)
    model.add_quant_dense(units=128)
    model.add_quant_dense(units=64)
    model.add_quant_dense(units=32)
    model.add_quant_dense(units=21)
    model.add_quant_dense(units=32)
    model.add_quant_dense(units=64)
    model.add_quant_dense(units=128)
    model.add_quant_dense(units=256)
    model.add_quant_dense(units=128)
    model.add_quant_dense(units=64)
    model.add_quant_dense(units=64)
    model.add_quant_dense(units=128)
    model.add_quant_dense(units=256)
    model.add_quant_dense(units=512)
    model.add_quant_dense(units=812)
    model.add_quant_dense(units=1024)
    model.add_quant_dense(units=1523)
    model.add_quant_dense(units=1854)
    model.add_quant_dense(units=2048)
    model.add_quant_dense(units=1854)
    model.add_quant_dense(units=1523)
    model.add_quant_dense(units=1024)
    model.add_quant_dense(units=812)
    model.add_quant_dense(units=512)
    model.add_quant_dense(units=128)
    model.add_quant_dense(units=64)
    model.add_quant_dense(units=32)
    model.add_quant_dense(units=21)
    model.add_quant_dense(units=32)
    model.add_quant_dense(units=64)
    model.add_quant_dense(units=128)
    model.add_quant_dense(units=256)
    model.add_quant_dense(units=128)
    model.add_quant_dense(units=64)
    model.add_quant_dense(units=64)
    model.add_quant_dense(units=128)
    model.add_quant_dense(units=256)
    model.add_quant_dense(units=512)
    model.add_quant_dense(units=812)
    model.add_quant_dense(units=1024)
    model.add_quant_dense(units=1523)
    model.add_quant_dense(units=1854)
    model.add_quant_dense(units=2048)
    model.add_quant_dense(units=1854)
    model.add_quant_dense(units=1523)
    model.add_quant_dense(units=1024)
    model.add_quant_dense(units=812)
    model.add_quant_dense(units=512)
    model.add_quant_dense(units=128)
    model.add_quant_dense(units=64)
    model.add_quant_dense(units=32)
    model.add_quant_dense(units=21)
    model.add_output(units=10)
    model.save()

def create_model8(): # 75, что-то не то с коэффициентами
    model = Model("model8")
    model.add_init()
    model.add_flatten()
    model.add_quant_dense(units=32)
    model.add_quant_dense(units=64)
    model.add_quant_dense(units=128)
    model.add_quant_dense(units=256)
    model.add_quant_dense(units=128)
    model.add_quant_dense(units=64)
    model.add_quant_dense(units=64)
    model.add_quant_dense(units=128)
    model.add_quant_dense(units=256)
    model.add_quant_dense(units=512)
    model.add_quant_dense(units=812)
    model.add_quant_dense(units=1024)
    model.add_quant_dense(units=1523)
    model.add_quant_dense(units=1854)
    model.add_quant_dense(units=2048)
    model.add_quant_dense(units=1854)
    model.add_quant_dense(units=1523)
    model.add_quant_dense(units=1024)
    model.add_quant_dense(units=812)
    model.add_quant_dense(units=512)
    model.add_quant_dense(units=128)
    model.add_quant_dense(units=64)
    model.add_quant_dense(units=32)
    model.add_quant_dense(units=21)
    model.add_quant_dense(units=32)
    model.add_quant_dense(units=64)
    model.add_quant_dense(units=128)
    model.add_quant_dense(units=256)
    model.add_quant_dense(units=128)
    model.add_quant_dense(units=64)
    model.add_quant_dense(units=64)
    model.add_quant_dense(units=128)
    model.add_quant_dense(units=256)
    model.add_quant_dense(units=512)
    model.add_quant_dense(units=812)
    model.add_quant_dense(units=1024)
    model.add_quant_dense(units=1523)
    model.add_quant_dense(units=1854)
    model.add_quant_dense(units=2048)
    model.add_quant_dense(units=1854)
    model.add_quant_dense(units=1523)
    model.add_quant_dense(units=1024)
    model.add_quant_dense(units=812)
    model.add_quant_dense(units=512)
    model.add_quant_dense(units=128)
    model.add_quant_dense(units=64)
    model.add_quant_dense(units=32)
    model.add_quant_dense(units=21)
    model.add_quant_dense(units=32)
    model.add_quant_dense(units=64)
    model.add_quant_dense(units=128)
    model.add_quant_dense(units=256)
    model.add_quant_dense(units=128)
    model.add_quant_dense(units=64)
    model.add_quant_dense(units=64)
    model.add_quant_dense(units=128)
    model.add_quant_dense(units=256)
    model.add_quant_dense(units=512)
    model.add_quant_dense(units=812)
    model.add_quant_dense(units=1024)
    model.add_quant_dense(units=1523)
    model.add_quant_dense(units=1854)
    model.add_quant_dense(units=2048)
    model.add_quant_dense(units=1854)
    model.add_quant_dense(units=1523)
    model.add_quant_dense(units=1024)
    model.add_quant_dense(units=812)
    model.add_quant_dense(units=512)
    model.add_quant_dense(units=128)
    model.add_quant_dense(units=64)
    model.add_quant_dense(units=32)
    model.add_quant_dense(units=21)
    model.add_output(units=10)
    model.save()


def create_model9(): # 35
    model = Model("model9")
    model.add_init()
    model.add_flatten()
    model.add_quant_dense(units=32)
    model.add_quant_dense(units=64)
    model.add_quant_dense(units=128)
    model.add_quant_dense(units=256)
    model.add_quant_dense(units=128)
    model.add_quant_dense(units=64)
    model.add_quant_dense(units=64)
    model.add_quant_dense(units=128)
    model.add_quant_dense(units=256)
    model.add_quant_dense(units=512)
    model.add_quant_dense(units=812)
    model.add_quant_dense(units=1024)
    model.add_quant_dense(units=1523)
    model.add_quant_dense(units=1854)
    model.add_quant_dense(units=2048)
    model.add_quant_dense(units=1854)
    model.add_quant_dense(units=1523)
    model.add_quant_dense(units=1024)
    model.add_quant_dense(units=812)
    model.add_quant_dense(units=512)
    model.add_quant_dense(units=128)
    model.add_quant_dense(units=64)
    model.add_quant_dense(units=32)
    model.add_quant_dense(units=21)
    model.add_quant_dense(units=32)
    model.add_quant_dense(units=64)
    model.add_quant_dense(units=128)
    model.add_quant_dense(units=256)
    model.add_quant_dense(units=128)
    model.add_quant_dense(units=64)
    model.add_quant_dense(units=32)
    model.add_quant_dense(units=21)
    model.add_output(units=10)
    model.save()


def create_model10(): # 51
    model = Model("model10")
    model.add_init()
    model.add_flatten()
    model.add_quant_dense(units=32)
    model.add_quant_dense(units=64)
    model.add_quant_dense(units=128)
    model.add_quant_dense(units=256)
    model.add_quant_dense(units=128)
    model.add_quant_dense(units=64)
    model.add_quant_dense(units=64)
    model.add_quant_dense(units=128)
    model.add_quant_dense(units=256)
    model.add_quant_dense(units=512)
    model.add_quant_dense(units=1024)
    model.add_quant_dense(units=512)
    model.add_quant_dense(units=128)
    model.add_quant_dense(units=64)
    model.add_quant_dense(units=32)
    model.add_quant_dense(units=21)
    model.add_quant_dense(units=32)
    model.add_quant_dense(units=64)
    model.add_quant_dense(units=128)
    model.add_quant_dense(units=256)
    model.add_quant_dense(units=128)
    model.add_quant_dense(units=64)
    model.add_quant_dense(units=64)
    model.add_quant_dense(units=128)
    model.add_quant_dense(units=256)
    model.add_quant_dense(units=512)
    model.add_quant_dense(units=1024)
    model.add_quant_dense(units=512)
    model.add_quant_dense(units=128)
    model.add_quant_dense(units=64)
    model.add_quant_dense(units=32)
    model.add_quant_dense(units=21)
    model.add_quant_dense(units=32)
    model.add_quant_dense(units=64)
    model.add_quant_dense(units=128)
    model.add_quant_dense(units=256)
    model.add_quant_dense(units=128)
    model.add_quant_dense(units=64)
    model.add_quant_dense(units=64)
    model.add_quant_dense(units=128)
    model.add_quant_dense(units=256)
    model.add_quant_dense(units=512)
    model.add_quant_dense(units=1024)
    model.add_quant_dense(units=512)
    model.add_quant_dense(units=128)
    model.add_quant_dense(units=64)
    model.add_quant_dense(units=32)
    model.add_quant_dense(units=21)
    model.add_output(units=10)
    model.save()


# create_model0()
# create_model1()
# create_model2()
# create_model3()
# create_model4()
# create_model5()
# create_model6()
# create_model7()
# create_model8()
# create_model9()
create_model10()
